#! /usr/bin/env sh

echo "creating schema ${PRIVATUS_DB_NAME}"

PGPASSWORD=${PRIVATUS_DB_ADMIN_PASSWORD} psql -d ${PRIVATUS_DB_NAME} -U${PRIVATUS_DB_ADMIN} -c "DROP SCHEMA IF EXISTS ${PRIVATUS_DB_NAME} CASCADE;"
PGPASSWORD=${PRIVATUS_DB_ADMIN_PASSWORD} psql -d ${PRIVATUS_DB_NAME} -U${PRIVATUS_DB_ADMIN} -c "CREATE SCHEMA IF NOT EXISTS ${PRIVATUS_DB_NAME} AUTHORIZATION ${PRIVATUS_DB_USER};"
