
#! /usr/bin/env sh

source ./scripts/db-config.sh

echo "removing all data from tables in ${PRIVATUS_DB_NAME}"
PGPASSWORD=${PRIVATUS_DB_ADMIN_PASSWORD} psql -d ${PRIVATUS_DB_NAME} -U${PRIVATUS_DB_ADMIN} -c "TRUNCATE ${PRIVATUS_DB_NAME}.tenancy CASCADE;"
PGPASSWORD=${PRIVATUS_DB_ADMIN_PASSWORD} psql -d ${PRIVATUS_DB_NAME} -U${PRIVATUS_DB_ADMIN} -c "TRUNCATE ${PRIVATUS_DB_NAME}.federation CASCADE;"
PGPASSWORD=${PRIVATUS_DB_ADMIN_PASSWORD} psql -d ${PRIVATUS_DB_NAME} -U${PRIVATUS_DB_ADMIN} -c "TRUNCATE ${PRIVATUS_DB_NAME}.training;"